### ISSUE TITLE
Font messes up with modeline icons?

### ISSUE THREAD

**Issue by facelesspanda** [ar1a/dotfiles#2]
Question mark because I'm really not sure here.
But when I install the patched iosevka custom fonts and activate `:ui (pretty-code +iosevka)`, I get all the cool ligatures, but for some reason, but the modeline dirty icon is not a floppy anymore:
![image](https://user-images.githubusercontent.com/13928490/67430382-66587d00-f5e2-11e9-9dfd-4d67f1544ddf.png)

(I know your own config doesn't even set iosevka as a font anymore, but the patched fonts are still up, so if they're out of date or incompatible with the default theme, it might be a good idea to indicate it in a comment or on the readme?)

**Comment by ar1a** [comment]
This is known, thanks for suggesting to put it in the readme, i'll do that!

This happens for the other ligature fonts iirc.

**Comment by facelesspanda** [comment]
yes it does. 
That said, Hlissner pushed a fix (https://github.com/hlissner/doom-emacs/commit/909c27796843a4b3e236354f96d0dd98266e5b97) for it that uses the font-awesome floppy instead of the material one if `pretty-code` is active with ligatures, so your readme might not need the changes

**Comment by ar1a** [comment]
ooooh, thanks!
